// generated by scripts/gen-web-config.mjs
window.__WF_CONFIG = {
  "sponsorUrl": "http://localhost:8788/sponsor",
  "portalUrl": "http://localhost:8790",
  "llmProxyUrl": "http://localhost:8787/llm",
  "zkGoogleClientId": "",
  "zkSaltUrl": "http://localhost:8789/salt",
  "zkProverUrl": ""
};
